# Generated by Django 4.2.7 on 2024-01-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_login_id', models.CharField(max_length=255, unique=True)),
                ('client_password', models.CharField(max_length=255)),
                ('client_confirm_password', models.CharField(max_length=255)),
                ('client_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_number', models.CharField(max_length=15)),
                ('client_DOB', models.DateField()),
                ('Client_address1', models.CharField(max_length=255)),
                ('client_address2', models.CharField(max_length=255)),
                ('client_city', models.CharField(max_length=100)),
                ('client_state', models.CharField(max_length=100)),
                ('client_country', models.CharField(max_length=100)),
                ('client_picture', models.ImageField(blank=True, upload_to='profile_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
