# Generated by Django 4.2.7 on 2024-01-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanagementapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdata',
            old_name='Client_address1',
            new_name='client_address1',
        ),
    ]
