# Generated by Django 4.2.7 on 2024-01-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanagementapp', '0002_rename_client_address1_clientdata_client_address1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='client_login_id',
            field=models.CharField(max_length=255),
        ),
    ]
