# Generated by Django 4.2.7 on 2024-01-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanagementapp', '0003_alter_clientdata_client_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='client_picture',
            field=models.ImageField(blank=True, upload_to='media\\uimg'),
        ),
    ]
