# Generated by Django 4.2.7 on 2024-01-10 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanagementapp', '0004_alter_clientdata_client_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='client_password',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Password must contain at least one digit, one character, and one special character.', regex='^(?=.*\\d)(?=.*[a-zA-Z])(?=.*[\\W_]).{8,}$')]),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='client_picture',
            field=models.ImageField(blank=True, upload_to='uimg/'),
        ),
    ]
