# Generated by Django 4.2.7 on 2024-01-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanagementapp', '0007_newpropertydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPropertyTypeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_type_name', models.CharField(max_length=100)),
                ('add_type_description', models.TextField()),
            ],
        ),
    ]
