# Generated by Django 4.2.7 on 2024-01-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanagementapp', '0009_newstatusdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpropertydata',
            name='seller_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
