# Generated by Django 4.2.7 on 2024-01-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanagementapp', '0010_newpropertydata_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpropertytypedata',
            name='seller_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newstatusdata',
            name='seller_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
