# Generated by Django 4.2.7 on 2024-01-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanagementapp', '0011_newpropertytypedata_seller_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='client_picture',
            field=models.ImageField(blank=True, upload_to='profilepics/'),
        ),
    ]
