# Generated by Django 4.2.7 on 2024-01-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanagementapp', '0012_alter_clientdata_client_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='client_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
