# Generated by Django 4.2.7 on 2024-01-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanagementapp', '0013_alter_clientdata_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='client_name',
            field=models.CharField(max_length=255),
        ),
    ]
