# Generated by Django 4.2.7 on 2024-01-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanagementapp', '0015_alter_clientdata_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=255)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buy_mobile', models.BigIntegerField()),
                ('buy_email', models.EmailField(max_length=254)),
                ('buy_dob', models.DateField()),
                ('buy_image', models.ImageField(upload_to='buy_profilepics/')),
                ('property_id', models.BigIntegerField()),
            ],
        ),
    ]
