# Generated by Django 4.2.7 on 2024-02-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanagementapp', '0016_sendenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendenquiry',
            name='confirmation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
