# Generated by Django 4.2.7 on 2024-02-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanagementapp', '0017_sendenquiry_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendenquiry',
            name='buy_mobile',
            field=models.BigIntegerField(null=True),
        ),
    ]
