# Generated by Django 4.2.7 on 2024-02-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanagementapp', '0022_soldproperty_alter_sendenquiry_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproperty',
            name='property_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
