# Generated by Django 4.2.7 on 2024-02-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanagementapp', '0023_soldproperty_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproperty',
            name='buyer_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
